# -*- coding: utf-8 -*-
"""Tubes Visdat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/184Rg2yg2ewPTpb0UW53yFYgL-LyIoHbv
"""

# Data handling
import pandas as pd

# Bokeh libraries
from bokeh.io import curdoc
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource, HoverTool, DatetimeTickFormatter, PrintfTickFormatter, Div
from bokeh.layouts import row, column, gridplot
from bokeh.models.widgets import Tabs, Panel

"""## Data Preparation"""

# !gdown --id 1xMrKRLFvmxcH24OPHv_XbXvEDreP_PxV

# Prepare the data
eMoney_ds = pd.read_excel("./data/Data Penggunaan Uang Elektronik di Indonesia 2010 - 2021.xlsx")
eMoney_ds.head()

"""## Output"""

# Determine where the visualization will be rendered
# output_file('filename.html')  # Render to static HTML, or 
# output_notebook()  # Render inline in a Jupyter Notebook

"""## Set Up Figure"""

def style_plot(plot):
    # axis styling, legend styling
    plot.outline_line_color = None
    plot.axis.axis_line_color = None
    plot.axis.major_tick_line_color = None
    plot.axis.minor_tick_line_color = None
    plot.xgrid.grid_line_color = None
    plot.xaxis.formatter = DatetimeTickFormatter(months = ["%b %Y"],
                                                 years = ["%Y"])
    plot.yaxis.formatter = PrintfTickFormatter(format = f'Rp%0.2f')
    #plot.legend.location = "top_left"
    #plot.legend.border_line_alpha = 0
    #plot.legend.background_fill_alpha = 0
    plot.title.text_font_size = "14pt"
    return plot

stat_figs = {}

"""# Volume uang elektronik"""

fig1 = figure(
    x_range = (min(eMoney_ds['Time']), max(eMoney_ds['Time'])),
    y_range = (0, max(eMoney_ds['Volume_transaksi_uang_Elektronik'])),
    x_axis_type = 'datetime',
    x_axis_label = 'Tanggal',
    plot_height=300, plot_width=600
) 

# fig.yaxis.formatter = PrintfTickFormatter(format = f'%')
fig1.xaxis.formatter = DatetimeTickFormatter(months = ["%b %Y"],
                                                 years = ["%Y"])
## VIEW
fig1.line("Time", "Volume_transaksi_uang_Elektronik",
        source = eMoney_ds)

## ADD INTERACTION
# Hover
tooltips = [
    ('Tanggal', '@Time{%b %Y}'),
    ('Volume Transaksi', '@Volume_transaksi_uang_Elektronik')
]

formatters = {'@Time': 'datetime'}

fig1.add_tools(HoverTool(tooltips = tooltips,
                        formatters = formatters))
# show(fig1)

stat_figs["Volume"] = fig1

"""# Nominal uang elektronik """

fig2 = figure(
    x_range = (min(eMoney_ds['Time']), max(eMoney_ds['Time'])),
    y_range = (0, max(eMoney_ds['Nominal_Transaksi_uang_Elektronik'])),
    x_axis_type = 'datetime',
    x_axis_label = 'Tanggal',
    plot_height=300, plot_width=600
) 

fig2.yaxis.formatter = PrintfTickFormatter(format = f'Rp%0.2f T')
fig2.xaxis.formatter = DatetimeTickFormatter(months = ["%b %Y"],
                                                 years = ["%Y"])

## VIEW
fig2.line("Time", "Nominal_Transaksi_uang_Elektronik",
        source = eMoney_ds)

## ADD INTERACTION
# Hover
tooltips = [
    ('Tanggal', '@Time{%b %Y}'),
    ('Nominal Transaksi', '@Nominal_Transaksi_uang_Elektronik{Rp%0.2f T}')
]

formatters = {'@Time': 'datetime',
             '@Nominal_Transaksi_uang_Elektronik': 'printf'}

fig2.add_tools(HoverTool(tooltips = tooltips,
                        formatters = formatters))
# show(fig2)

stat_figs["Nominal"] = fig2

"""# Volume uang elektronik dan Nominal uang elektronik """

fig1.x_range = fig2.x_range
fig3 = row(fig1,fig2)
# show(fig3)

#add title
isi = """<h1>Visualisasi Penggunaan Uang Elektronik</h1>
<h3><i>Penggunaan uang elektronik di Indonesia pada rentang tahun 2010 - 2021</i><h3>"""
title = Div(text=isi)
#add widget panel and tab
fig1_panel = Panel(child=fig1, title='Volume Uang Elektronik')
fig2_panel = Panel(child=fig2, title='Nominal Uang Elektronik ')
fig3_panel = Panel(child=fig3, title='Perbandingan Volume dan Nominal uang elektronik' )
tab = Tabs(tabs=[fig1_panel, fig2_panel, fig3_panel])
#add layout
layout = column(title,tab)
curdoc().add_root(layout)

# output_file('Uang_elektronik_Indonesia.html')